### ISSUE TITLE
Typo/broken link in readme commented code

### ISSUE THREAD

**Issue by Hitman007** [eugene-manuilov/wp-codeception#10]
It says:
http://codeception.com/docs/04-AcceptanceTests#PHP-Browser

It should say:
http://codeception.com/docs/03-AcceptanceTests#PHP-Browser

ps - FREAKIN AWESOME PLUGIN!

**Comment by eugene-manuilov** [comment]
Thanks man! I have fixed broken links. Should be fine now.
