### ISSUE TITLE
Publish plugin on wordpress.org

### ISSUE THREAD

**Issue by eugene-manuilov** [eugene-manuilov/wp-codeception#11]
Hey @tlovett1,

Can we publish this plugin on wordpress.org? If we publish it there, then it will appear on the http://wpackagist.org/ site and everybody will be able to install it via composer as a dependecy. What do you think?

If we go this route, then I will need to prepare a new build which will contain proper composer.json file and dependant libraries.

**Comment by tlovett1** [comment]
Any reason not to just add this to Packagist? Adding to WP.org is a bit annoying.

**Comment by eugene-manuilov** [comment]
The wpackagist.org is WordPress oriented composer repository, so it looks a bit more "attractive" than standard packagist. Anyway packagist would work too if it is hard to push the plugin to wp.org.

**Comment by tlovett1** [comment]
Whatever you want to do works :) If you want to maintain the WP.org plugin, that's cool. Probably want to add a readme.txt if you go that route.

**Comment by fuhton** [comment]
Starting to use this and it'd be helpful if it was in a public composer list ( either wpackagist or packagist ). Would prefer not to install it as a plugin, but in the vendor dir.

**Comment by eugene-manuilov** [comment]
Updated composer.json file, so we can publish it at packagist.com. @tlovett1 do you have access to 10up account on packagist?

**Comment by tlovett1** [comment]
Nope, can you ping the Senior Web Engineer room in Hipchat. Maybe @johnpbloch ?

**Comment by johnpbloch** [comment]
This has been added to packagist and set up to auto update.

**Comment by eugene-manuilov** [comment]
Thanks!
