### ISSUE TITLE
npm is throwing a warning because of wrong licence

### ISSUE THREAD

**Issue by dimitrismitsis** [eugene-manuilov/wp-codeception#16]
Hi fellas,

Thank you for this nice plugin :)

While trying to install it, I saw that npm didn't actually start as in some latest update, it changed the way it handles licence.

I believe this can be fixed by adjusting the licence in your package.json to "GPL-2.0+"

**Comment by eugene-manuilov** [comment]
Thanks Dimitris!

I have updated the license to be compliant with SPDX License List. Let me know if you find anything else. Closing this thread for now.

**Comment by egamipeaks** [comment]
I am getting this warning
