### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by AaronHolbrook** [eugene-manuilov/wp-codeception#4]
This took a bit to get running, I think we could ease that with more documentation

**Comment by jamesmehorter** [comment]
Hey all.. how 'bout we give these docs some tlc?.. a little.. lovin..

Any thoughts, snippets, examples, suggestions?!?... lay it out here! :) We can work in feature/documentation; starting small and submitting PRs. I'll push some initial stuff to get the ball roll and will try to contribute as much as possible.
